# Backward-compatible constants surface.
#
# All public constant names the flat constants.py used to export remain
# importable here so the 11 importer scripts keep working unchanged. New
# canonical names from the split are re-exported too. Renamed constants keep a
# deprecated alias under their old name (and vice versa) for a clean migration.

from .exclusions import (
    ARCHAIC_OBSOLETE_BLOCKLIST,
    EXCLUDED_WORDS,
    LOW_FLAIR_EXCLUSIONS,
)
from .pipeline import (
    CACHE_FILE,
    ED_STEM_MIN_LENGTH,
    MAX_WORD_LENGTH,
    MIN_WORD_LENGTH,
    TARGETED_LEAKS,
    ZIPF_MAX_THRESHOLD,
    ZIPF_MIN_THRESHOLD,
)
from .suffixes import (
    BUREAUCRATIC_SUFFIXES,
    CLINICAL_SUFFIXES,
    EXCLUDED_SUFFIXES,
)
from .whitelist import (
    BEHAVIORAL_ARCHETYPES,
    ED_SUFFIX_KEEP,
    EXPRESSIVE_RESCUE,
    GRAMMAR_LINGUISTIC_TERMS,
    HIGH_FLAIR_BASE_WORDS,
    NAMED_INDIVIDUAL_BLOCKLIST,
    NOUN_SUFFIX_KEEP,
    PRIMARY_CORE_WHITELIST,
    RESCUE_WORDS,
    SPELLING_VARIANTS,
    UN_PREFIX_KEEP,
    WHITELIST,
)
from .wordnet import (
    CONCRETE_LEXFILES,
    DEFINITION_EXCLUSION_KEYWORDS,
    DEFINITION_ORIGIN_MARKERS,
    EXCLUDED_HYPERNYMS,
    EXCLUDED_POS,
    EXCLUDED_RELATED_TARGETS,
    NAMED_INDIVIDUAL_DEFINITION_REGEX,
    NAMED_INSTANCE_CATEGORIES,
    NOUN_LEXFILES,
    TAXONOMY_EXCLUSION_GROUPS,
    TAXONOMY_ROOT_EXCLUSIONS,
)

# --- Deprecated aliases (old flat-constants names) -------------------------

# renamed constants
ARCHAIC_OBSCLETE_BLOCKLIST = ARCHAIC_OBSOLETE_BLOCKLIST  # typo fixed
BLOAT_SUFFIXES = BUREAUCRATIC_SUFFIXES
CLINICAL_STEM_SUFFIXES = CLINICAL_SUFFIXES
DEFINITIONAL_EXCLUSION_KEYWORDS = DEFINITION_EXCLUSION_KEYWORDS
ED_KEEP = ED_SUFFIX_KEEP
EXCLUDED_TARGETS = EXCLUDED_RELATED_TARGETS
ROOT_HYPONYM_EXCLUSION_GROUPS = TAXONOMY_EXCLUSION_GROUPS
SUFFIX_KEEP = NOUN_SUFFIX_KEEP
UN_PREFIX_WHITELIST = UN_PREFIX_KEEP

__all__ = [
    'ARCHAIC_OBSCLETE_BLOCKLIST',
    'ARCHAIC_OBSOLETE_BLOCKLIST',
    'BEHAVIORAL_ARCHETYPES',
    'BLOAT_SUFFIXES',
    'BUREAUCRATIC_SUFFIXES',
    'CACHE_FILE',
    'CLINICAL_STEM_SUFFIXES',
    'CLINICAL_SUFFIXES',
    'CONCRETE_LEXFILES',
    'DEFINITIONAL_EXCLUSION_KEYWORDS',
    'DEFINITION_EXCLUSION_KEYWORDS',
    'DEFINITION_ORIGIN_MARKERS',
    'ED_KEEP',
    'ED_STEM_MIN_LENGTH',
    'ED_SUFFIX_KEEP',
    'EXCLUDED_HYPERNYMS',
    'EXCLUDED_POS',
    'EXCLUDED_RELATED_TARGETS',
    'EXCLUDED_SUFFIXES',
    'EXCLUDED_TARGETS',
    'EXCLUDED_WORDS',
    'EXPRESSIVE_RESCUE',
    'GRAMMAR_LINGUISTIC_TERMS',
    'HIGH_FLAIR_BASE_WORDS',
    'LOW_FLAIR_EXCLUSIONS',
    'MAX_WORD_LENGTH',
    'MIN_WORD_LENGTH',
    'NAMED_INDIVIDUAL_BLOCKLIST',
    'NAMED_INDIVIDUAL_DEFINITION_REGEX',
    'NAMED_INSTANCE_CATEGORIES',
    'NOUN_LEXFILES',
    'NOUN_SUFFIX_KEEP',
    'PRIMARY_CORE_WHITELIST',
    'RESCUE_WORDS',
    'ROOT_HYPONYM_EXCLUSION_GROUPS',
    'SPELLING_VARIANTS',
    'SUFFIX_KEEP',
    'TARGETED_LEAKS',
    'TAXONOMY_EXCLUSION_GROUPS',
    'TAXONOMY_ROOT_EXCLUSIONS',
    'UN_PREFIX_KEEP',
    'UN_PREFIX_WHITELIST',
    'WHITELIST',
    'ZIPF_MAX_THRESHOLD',
    'ZIPF_MIN_THRESHOLD',
]
