# WordNet taxonomy, lexfile, and definition heuristics used to reject
# clinical / STEM / junk semantics. Provenance: extracted verbatim from the
# flat constants.py (pre-refactor). Renames applied per change spec:
#   ROOT_HYPONYM_EXCLUSION_GROUPS -> TAXONOMY_EXCLUSION_GROUPS
#   DEFINITIONAL_EXCLUSION_KEYWORDS -> DEFINITION_EXCLUSION_KEYWORDS
#   EXCLUDED_TARGETS -> EXCLUDED_RELATED_TARGETS
# The EXHAUSTIVE_UNWANTED_HYPERNYMS alias is DELETED; builders now point at
# TAXONOMY_ROOT_EXCLUSIONS.

import re

# Categories of instance-hypernyms (and direct hypernyms) that mark a word as a
# named entity (person, place, ship, deity, ...). Proper nouns arrive lowercase
# in the raw web2 source, so presence of these categories is the reliable
# named-entity detector.
NAMED_INSTANCE_CATEGORIES = {
    # deity kinds
    'greek deity',
    'roman deity',
    'norse deity',
    'hindu deity',
    'egyptian deity',
    'celtic deity',
    'semitic deity',
    'greco-roman deity',
    'phrygian deity',
    'teutonic deity',
    'japanese deity',
    'god',
    'goddess',
    # named entities / people
    'mythical being',
    'fictional character',
    'saint',
    'patron saint',
    'constellation',
    'sign of the zodiac',
    'star',
    'binary star',
    'giant star',
    'supergiant',
    'lodestar',
    'asteroid',
    'terrestrial planet',
    'superior planet',
    'historic period',
    'epoch',
    'eon',
    'siege',
    'pitched battle',
    'writer',
    'poet',
    'painter',
    'physicist',
    'nuclear physicist',
    'chemist',
    'mathematician',
    'philosopher',
    'theologian',
    'psychologist',
    'biochemist',
    'bacteriologist',
    'physiologist',
    'lexicographer',
    'historian',
    'astronomer',
    'navigator',
    'explorer',
    'educator',
    'missionary',
    'suffragist',
    'abolitionist',
    'civil rights leader',
    'feminist',
    'economist',
    'financier',
    'industrialist',
    'inventor',
    'architect',
    'sculptor',
    'dramatist',
    'composer',
    'songwriter',
    'actor',
    'actress',
    'comedian',
    'comedienne',
    'dancer',
    'choreographer',
    'singer',
    'rock star',
    'jazz musician',
    'film maker',
    'ballplayer',
    'tennis player',
    'golfer',
    'violin maker',
    'printer',
    'publisher',
    'journalist',
    'doctor',
    'lawyer',
    'general',
    'solon',
    'king',
    'king of england',
    'queen',
    'emperor',
    'roman emperor',
    'president of the united states',
    'chief justice',
    'american revolutionary leader',
    'religious leader',
    'prophet',
    'apostle',
    'evangelist',
    'patriarch',
    'jew',
    'son',
    'wife',
    'man',
    'avatar',
    'book',
    'sacred text',
    'hagiographa',
    'browser',
    # places / geographic names
    'city',
    'town',
    'village',
    'port',
    'port of entry',
    'capital',
    'national capital',
    'state capital',
    'american state',
    'state',
    'county',
    'district',
    'region',
    'french region',
    'geographical area',
    'island',
    'archipelago',
    'mountain peak',
    'hill',
    'volcano',
    'lake',
    'sea',
    'river',
    'colony',
    'university',
    # countries
    'country',
    'african country',
    'asian country',
    'south american country',
    'european country',
    'state with limited recognition',
    # ships & named objects
    'ship',
    'muse',
    'titaness',
    'hypostasis',
    'spiritual being',
    'festival',
}

# Detects named individuals (people) whose WordNet definitions contain
# birth-death year ranges, e.g. waugh -> 'English author of satirical novels (1903-1966)'.
# Proper nouns arrive lowercase in the raw web2 source, so this regex is the
# reliable detector that a case-based filter cannot provide.
NAMED_INDIVIDUAL_DEFINITION_REGEX = r'\(\d{3,4}[-–]\d{3,4}\)'

# Clean Grouped Root Hyponym Exclusions (Eliminates subtrees at root level)
TAXONOMY_EXCLUSION_GROUPS = {
    'organism': {
        'organism',
        'plant',
        'vascular_plant',
        'herb',
        'shrub',
        'tree',
        'flower',
        'animal',
        'bird',
        'fish',
        'insect',
        'reptile',
        'mammal',
        'mollusk',
        'microorganism',
        'alga',
        'woody_plant',
    },
    'person': {
        'person',
        'individual',
        'man',
        'woman',
        'child',
        'causal agent',
        'religious_person',
    },
    'artifact': {
        'artifact',
        'artefact',
        'structure',
        'edifice',
        'building',
        'container',
        'vessel',
        'receptacle',
        'garment',
        'clothing',
        'fabric',
        'apparel',
        'headgear',
        'device',
        'instrument',
        'appliance',
        'tool',
        'measuring_instrument',
        'vehicle',
        'conveyance',
        'signal',
        'signaling_device',
        'acoustic_device',
        'musical_instrument',
        'bowed_stringed_instrument',
    },
    'substance_and_medicine': {
        'element',
        'metal',
        'mineral',
        'rock',
        'chemical_compound',
        'organic_compound',
        'substance',
        'food',
        'beverage',
        'drink',
        'dish',
        'symptom',
        'inflammation',
        'disease',
        'neoplasm',
        'carcinoma',
        'medical_condition',
        'artery',
        'bone',
        'drug',
        'controlled_substance',
        'pathology',
        'tissue',
        'sac',
        'liquid_body_substance',
        'body_substance',
        'water',
        'liquid',
        'fluid',
        'body_waste',
        'phobia',
        'anxiety_disorder',
        'cell',
        'plant_tissue',
        'animal_tissue',
        'membrane',
        'protoplasm',
    },
    'geography': {'location', 'geographic_area', 'city', 'port', 'region', 'town'},
    'ideology_lore_science_math_color': {
        'Greek_deity',
        'deity',
        'mythical_being',
        'god',
        'goddess',
        'theology',
        'religion',
        'religious_doctrine',
        'faith',
        'creed',
        'political_orientation',
        'politics',
        'doctrine',
        'ism',
        'color',
        'chromatic_color',
        'visual_property',
        'singing',
        'vocalization',
        'holiday',
        'sport',
        'athletics',
        'game',
        'mathematics',
        'discipline',
        'branch_of_knowledge',
        'science',
        'zoology',
        'greek_letter',
        'letter_of_the_alphabet',
        'medicine',
    },
    'measurement_and_connection': {
        'measure',
        'magnitude',
        'unit_of_measurement',
        'system_of_measurement',
        'join',
        'joint',
        'unite',
        'attachment',
        'fastener',
        'metric_unit',
    },
    'sound_and_onomatopoeia': {
        'sound',
        'noise',
        'cry',
        'utter',
        'reflex',
        'emit',
        'rain',
    },
}

# Flattened set of all root hyponym exclusions for fast O(1) checks
TAXONOMY_ROOT_EXCLUSIONS = set().union(*TAXONOMY_EXCLUSION_GROUPS.values())

# Substring keywords that mark a definition as clinical / STEM / physical /
# generic object or concept. A word whose definition contains any of these is
# dropped (is_definitional_excluded in the cache).
DEFINITION_EXCLUSION_KEYWORDS = (
    'container',
    'vessel',
    'receptacle',
    'structure',
    'edifice',
    'garment',
    'clothing',
    'fabric',
    'textile',
    'apparel',
    'headgear',
    'tool',
    'implement',
    'device',
    'apparatus',
    'measuring',
    'chemical',
    'mineral',
    'alloy',
    'element',
    'genus of',
    'family of',
    'species of',
    'shrub of',
    'tree of',
    'herb of',
    'fish of',
    'bird of',
    'branch of zoology',
    'branch of biology',
    'branch of chemistry',
    'branch of physics',
    'branch of acoustics',
    'branch of mathematics',
    'mathematical',
    'mathematics',
    'algebraic',
    'formula',
    'algorithm',
    'excrement',
    'excretion',
    'stool',
    'sled',
    'sledge',
    'sleigh',
    'vehicle',
    'jail',
    'prison',
    'workhouse',
    'clink',
    'gaol',
    'jailhouse',
    'pokey',
    'poorhouse',
    'racecourse',
    'raceway',
    'drifter',
    'floater',
    'vagabond',
    'vagrant',
    'hydrocarbon',
    'flying dutchman',
    'leakey',
    'street name',
    'patois',
    'lingo',
    'rhyming slang',
    'canine',
    'teahouse',
    'tearoom',
    'storeroom',
    'stowage',
    'analgesic',
    'anodyne',
    'painkiller',
    'ointment',
    'salve',
    'balm',
    'beet',
    'beetroot',
    'weapon',
    'gun',
    'artillery',
    'liqueur',
    'maraschino',
    'cordial',
    'podcast',
    'conservatoire',
    'conservatory',
    'legal damages',
    'actual damages',
    'punitive damages',
    'compensatory damages',
    'quantity',
    'amount',
    'number',
    'measurement',
    'location',
    'geography',
    'country',
    'game',
    'sport',
    'race',
    'geological',
    'anatomy',
    'medicine',
    'wart',
    'dribble',
    'snag',
    'smack',
    'caput',
    'occipital protuberance',
    'frontal eminence',
    'discharge',
    'splotch',
    'estrogen',
    'androgen',
    'jaundice',
    'amino acid',
    'inflammation',
    'surgical removal',
    'chemical compound',
    'enzyme',
    'organic compound',
    'ester',
    'acid',
    'secretion',
    'tumor',
    'carcinoma',
    'gland',
    'medical',
    'alkaloid',
    'adenocarcinoma',
    'alkaline',
    'alexia',
    'alga',
    'muscle',
    'artery',
    'vein',
    'tissue',
    'ship',
    'boat',
    'zirconium oxide',
    'yodel',
    'singing',
    'holiday',
    'religion',
    'religious',
    'theology',
    'theological',
    'deity',
    'god',
    'goddess',
    'church',
    'doctrine',
    'political',
    'politics',
    'branch of physics',
    'acoustics',
    'sound',
    'carcinogen',
    'bone',
    'cortex',
    'cyst',
    'diphtheria',
    'eczema',
    'emphysema',
    'femur',
    'lactate',
    'lymph',
    'graft',
    'neural structure',
    'contagious disease',
    'skin disease',
    'respiratory disease',
    'vertebra',
    'violin',
    'volume',
    'weight',
    'weld',
    'whistle',
    'phobia',
    'morbid fear',
    'greek letter',
    'letter of the alphabet',
    'zoology',
    'zigzag',
    'zonal',
    'colour',
    'reddish',
    'bluish',
    'yellowish',
    'whitish',
    'blackish',
    'greenish',
    'purplish',
    'pinkish',
    'cauda',
    'adipose',
    'alveolar',
    'anabolic',
    'anaerobic',
    'antibacterial',
    'atrial',
    'carotid',
    'celiac',
    'cochlear',
    'cornea',
    'cytoplasm',
    'dermal',
    'dermatology',
    'dielectric',
    'electrostatic',
    'ischemic',
    'necrosis',
    'ventricle',
    'acrobat',
    'acrobatic',
)

# Exact-match direct-hypernym terms that indicate clinical/STEM/junk semantics.
# Matched via set intersection against the cached direct_hypernyms, so the
# noisy substring collisions ('sac' in 'sacrament', 'organ' in 'organic',
# 'sport' in 'transport', 'color' in 'colorlessness', etc.) are eliminated.
EXCLUDED_HYPERNYMS = {
    # disease / anxiety
    'disease',
    'autoimmune disease',
    'blood disease',
    'cardiovascular disease',
    'communicable disease',
    'contagious disease',
    'coronavirus disease',
    'deficiency disease',
    'epidemic disease',
    'eye disease',
    'genetic disease',
    'glandular disease',
    'heart disease',
    'infectious disease',
    'inflammatory disease',
    'kidney disease',
    'liver disease',
    'periodontal disease',
    'plant disease',
    'respiratory disease',
    'rickettsial disease',
    'skin disease',
    'venereal disease',
    'anxiety disorder',
    'simple phobia',
    'social phobia',
    # chemical / process
    'chemical process',
    'chemical analysis',
    'chemical reaction',
    'compound',
    'ester',
    'hormone',
    'alkaloid',
    'acid',
    'amino acid',
    'controlled substance',
    'phytochemical',
    # anatomy / pathology
    'organ',
    'reproductive organ',
    'sense organ',
    'internal organ',
    'external organ',
    'bone',
    'tissue',
    'membrane',
    'gland',
    'endocrine gland',
    'carcinoma',
    'pathology',
    'microorganism',
    # clinical process / genetics
    'eating disorder',
    'pathologic process',
    'gene',
    'regional anesthesia',
    # keeps the substring loop's good-word catches
    'sacrament',
}

# Sense-relation targets (derivation/pertainym) that mark a word as clinical.
# A word is dropped when ANY of its related_targets lands in this set
# (e.g. breathless->dyspnea, rabid->rabies, feverish->feverishness).
EXCLUDED_RELATED_TARGETS = {
    'dyspnea',
    'debility',
    'rabies',
    'arthritis',
    'rheumatism',
    'asphyxia',
    'aphonia',
    'feverishness',
    'melancholia',
    'unwellness',
    'pathology',
    'discriminate',
}

# Concrete lexfiles: a word whose lexfiles are all concrete AND whose only root
# is 'physical entity' is a mundane physical object (rule_concrete_only).
CONCRETE_LEXFILES = {
    'noun.artifact',
    'noun.object',
    'noun.plant',
    'noun.animal',
    'noun.food',
    'noun.body',
    'noun.substance',
    'noun.location',
}

# Every noun lexfile (concrete + abstract). Used to detect whether a word has a
# non-noun sense / to scope noun-only rules. (New constant: did not exist in the
# flat constants.py; added so the rules registry can validate noun-only targets.)
NOUN_LEXFILES = CONCRETE_LEXFILES | {
    'noun.act',
    'noun.attribute',
    'noun.cognition',
    'noun.communication',
    'noun.event',
    'noun.feeling',
    'noun.group',
    'noun.motive',
    'noun.person',
    'noun.phenomenon',
    'noun.process',
    'noun.quantity',
    'noun.relation',
    'noun.shape',
    'noun.state',
    'noun.time',
}

# Detects region/religion/culture-of-origin markers in definitions - foreign or niche-flavored
# vocabulary is dropped to keep the list culturally-neutral common English.
DEFINITION_ORIGIN_MARKERS = re.compile(
    r'\b(india|indian|pakistan|russia|siberia|africa|african|middle east|arabia|arabic|'
    r'scotland|scottish|ireland|irish|wales|welsh|gaul|gaelic|celtic|french|spanish|'
    r'italian|german|dutch|portuguese|japanese|chinese|turkish|greek|roman|latin|'
    r'hebrew|yiddish|persian|hindu|buddhist|sanskrit|islam|muslim|christian|catholic|'
    r'jewish|veda|quran|bible|scripture|mythology|folklore|legend|fairy tale|elf|deity)\b',
    re.IGNORECASE,
)

# POS tags that never qualify for the curated list: closed-class / non-content
# parts of speech.
EXCLUDED_POS = {'pron', 'det', 'prep', 'conj', 'part', 'intj', 'num'}
